namespace Bible_Blazer_PWA.Parameters
{
    public enum Parameters
    {
        FontSize,
        MainBackground,
        ToolsBg,
        HideTools,
        FirstLevelBg,
        FirstLevelBodyBg,
        FirstLevelMarginTop,
        FirstLevelFontWeight,
        SecondLevelBg,
        SecondLevelBodyBg,
        SecondLevelMarginTop,
        SecondLevelFontWeight,
        ThirdLevelBg,
        ThirdLevelBodyBg,
        ThirdLevelMarginTop,
        ThirdLevelFontWeight,
        BlocksPadding,
        AreReferencesOpened,
        CollapseLevel,
        HideBlocksBorders,
        BlocksPaddingLeft,
        BlocksPaddingRight,
        StartVersesOnANewLine,
        BibleRefBgColor,
        BibleRefFontColor,
        BibleRefHighlightColor
    }
}